#!/usr/bin/env python
import traceback
import rospy
from scout.ros.controller import RosController


def main():
    rospy.init_node('scout_controller', anonymous=True)
    RosController().run()


if __name__ == '__main__':
    main()
