#!/usr/bin/env python
import traceback
import rospy
from scout.ros.controller import RosController


def main():
    rospy.init_node('scout_controller', anonymous=True)
    #parameter = rospy.get_param("~param", "default_value")
    RosController().run()


if __name__ == '__main__':
    main()
