#!/usr/bin/env python
import traceback
import rospy
from subprocess import Popen, TimeoutExpired


def main():
    rospy.init_node("scout_ds4drv", anonymous=True)
    p = Popen(["ds4drv", "--hidraw"])
    while not rospy.is_shutdown():
        try:
            p.wait(timeout=3)
        except TimeoutExpired:
            pass
    p.kill()


if __name__ == '__main__':
    main()
