version: "3.3"
services:
  scout:
    image: "banzzaj/scout-ros-av"
    devices:
      - "/dev/ydlidar:/dev/ydlidar"
      - "/dev/input/js0:/dev/input/js0"
      - "/dev/ttyACM0:/dev/ttyACM0"
      - "/dev/ttyACM1:/dev/ttyACM1"
    restart: always
    network_mode: "host"
    tty: true

