name: Build and publish AV docker image

on:
  push:
    branches: 'master'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./docker/nano/av/Dockerfile
          push: true
          tags:
            - banzzaj/scout-ros-av:${{ steps.extract_branch.outputs.branch }}
            - banzzaj/scout-ros-av:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

